### ISSUE TITLE
How to add support for register read write?

### ISSUE THREAD

**Issue by drobinkent** [p4lang/p4runtime-shell#52]
How to add support for register read write? Any idea? Or is it already implemented at some place?

**Comment by antoninbas** [comment]
Easiest thing to do if you want to add support is to look at how counters are handled and replicate it for registers. Most changes (save for unit tests) should be localized to this file: https://github.com/p4lang/p4runtime-shell/blob/master/p4runtime_sh/shell.py

However, because PI does not implement support for registers (https://github.com/p4lang/PI/issues/376), you would not be able to use p4runtime-shell to access registers when using bmv2.

**Comment by drobinkent** [comment]
thanks
