### ISSUE TITLE
PacketIO sniff() issue

### ISSUE THREAD

**Issue by EmanueleGallone** [p4lang/p4runtime-shell#73]
Hi
I'm actually using the p4runtime-shell with the latest feature (#55), more precisely the function `sniff`. While testing this feature I noticed that the sniff blocks indefinitely if the rate of incoming Packet_INs is greater than the provided `timeout`.

it blocks here https://github.com/p4lang/p4runtime-shell/blob/45ac13f6310f3cd23c2426269aac30b66ad96f93/p4runtime_sh/shell.py#L2415
apparently, the timeout within the `self.packet_in_queue.get()` function resets everytime a new packet_in is dequeued.

The reason why I opened this issue is because I was expecting a behaviour similar to scapy's `sniff()`.

**Comment by antoninbas** [comment]
I do agree that it's a bit surprising. I think it's natural for someone to expect that the function will return after the timeout expires, and it shouldn't be a per packet timeout. @Yi-Tseng any thoughts?

@EmanueleGallone feel free to open a PR to address this if you want

**Comment by Yi-Tseng** [comment]
Per packet timeout is my initial design, and I didn't realize this issue because I only test few packets manually.
I think it is a good idea to change this to make the function return after a certain period.
I was also thinking about changing the behavior of this function. 
For example, apply the function when we receive a packet-in instead of applying all packet-ins after the timeout.
Feel free to open a pull request to change this, thanks!
